name: Bug Report
description: Report something that's broken
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Be specific. Include error messages, polestar version, and OS.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
    validations:
      required: true
